### ISSUE TITLE
Vko 6 code review

### ISSUE THREAD

**Issue by kaarleol** [ah-pasila/ot-running-calendar#1]
Projekti ladattu 12.12.2023 klo 17:20

## Sovelluksen toiminta
Toiminnallisuutta on aloitettu, rekisteröinti toimii ja juoksuja voi lisätä.

Tällä hetkellä sovellus kaatuu jos luo käyttäjän jolla jo olemassaoleva käyttäjänimi. Käyttäjää luodessa on myös mahdollista syöttää pelkkiä tyhjiä syötteitä. Juoksuja ei taideta myöskään tällä hetkellä yhdistää käyttäjälle vaan tietokantaan tallentuu NULL käyttäjän kohdalle.

Nämä ongelmat toki varmasti korjataan ajallaan kun sovellusta kehitetään.

### Kommentit

Luokkia on kommentoitu hyvin mikä helpottaa koodin ymmärtämistä. 

Koodin rakenteen yhtenäistämiseksi suosittelisin kuitenkin käyttämään vain yhtä kommentointityyliä. Osassa koodia on käytetty docstringeja ja osassa normaaleja kommentteja. 

Esim. run_calendar_service.py vs initalize_database.py. 

Lisäksi kommenttien kieli vaihtelee suomen ja englannin välillä. Englannissa pysyttely koodiin liittyvissä asioissa taitaa olla yleinen ohjeistus ainakin suurimmalla osalla kursseista?

### Nimet

Nimet ovat kuvaavia ja enimmääkseen oikean muotoisia. Huomaa kuitenkin että moniosaisissa luokkien nimissä tulisi käyttää PascalCasea kurssin [nimeämisohjeiden](https://ohjelmistotekniikka-hy.github.io/python/koodin-laatuvaatimukset) mukaan. Eli run_calendar_servicen luokka Run_calendar_servicen nimen pitäisi olla RunCalendarService.

### SQL-n tyyli
SQL-komennoissa SQL:n omat avainsanat kirjoitetaan yleensä isoilla kirjaimilla. Pienten alkukirjainten käyttö taitaa olla myös sallittua, mutta pysyttele samassa käytännössä. Run_repository.py:ssä on käytetty sekä isoja kirjaimia, että pieniä kirjaimia, ja initalize_databasessa pelkkiä pieniä kirjaimia.

### Metodien erottelu

Luokan UI add_plan metodi alkaa venymään, joten se voisi olla hyvä paloitella osiksi, esim. luomalla oman metodin sovelluksen käynnistämisen tulostuksille ja oman käyttäjän syötteen silmukalle.

Tulostus olisi varmaan hyvä eritellä käyttöliittymän omaksi metodiksi. Esim run_repositoryn return_all_runs tulostaa itse komentoriville, vaikka hyvänä käytäntönä varmaan olisi palauttaa ne käyttöliittymälle, joka hoitaa tulostuksen

![Screenshot](https://github.com/ah-pasila/ot-running-calendar/assets/127772376/51c1cd3d-d3c1-41e7-909a-bf11312389d3)

Samoin UI-luokan tulostukset

![Screenshot](https://github.com/ah-pasila/ot-running-calendar/assets/127772376/631ab50f-8d62-4b39-9397-f69e19b812ba)

### Testit 

Testit eivät tällä hetkellä toimi. Voi olla että koodin rakenne on muuttunut testin kirjoittamisen jälkeen, sillä en löydä funktioita joita testissä yritetään kutsua. Huomaa  että testissäsi self.run ei ole edes määritelty. 

### Overall

Toimintoja on alettu tekemään, sovelluksella on toimiva pohja ja koodi on helppolukuista ja enimmäkseen siistiä. Tuosta on hyvä jatkaa. Tsemppiä!

**Comment by ah-pasila** [comment]
Kiitos ajatuksella tehdystä palautteesta, siitä on paljon hyötyä projektia edistäessä!

**Comment by ah-pasila** [comment]
Lähes kaikki huomiot saatu loppupalautuksessa otettua jollain tapaa huomioon (pl. tyhjän merkkijonon tallentaminen käyttäjänimeksi kertaluontoisesti jäi harmillisesti mukaan).
